### ISSUE TITLE
Install Foundation and choose color scheme

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#14]
Do we have any color scheme thoughts??? Some pulled from colourlovers w/ potential (feel free to add your own):
- http://www.colourlovers.com/palette/4020275/breathing_fairy_dust
- http://www.colourlovers.com/palette/4015134/Youre_Sixteen
- http://www.colourlovers.com/palette/4022958/The_Blackest_Star
- http://www.colourlovers.com/palette/3790005/Mystery_Moonbather
- http://www.colourlovers.com/palette/3736312/Agates_Mystery%E2%98%85
- http://www.colourlovers.com/palette/3947631/The_Mystery_Zone
- http://www.colourlovers.com/palette/3801566/Mysterious_Mutiny
- http://www.colourlovers.com/palette/3837638/Forest_Mystery%E2%97%8B
- http://www.colourlovers.com/palette/3853144/Mysterious_Mind
- http://www.colourlovers.com/palette/4031670/mysterious_ways

**Comment by sublimemarch** [comment]
Selected palette: http://www.colourlovers.com/palette/4022958/The_Blackest_Star
