### ISSUE TITLE
Add wounds to character model and sheet

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#26]
I wasn't sure when I was putting the character model together whether wounds would be a variable number of boxes or static, but based on the rules doc it looks like it's static. (Confirm w/ Mark?) Wounds levels should be added to the character model so that they can be displayed on the character sheet.

(I'm assuming that we may want them to carry over between play sessions; if we don't, we don't care and can just print them by default and leave them off the sheet editing form.)

**Comment by sublimemarch** [comment]
Yeah, if we don't want them to carry over, they should just be the empty boxes. We'll need to ask Mark. Actually, it could be a great idea if we had him get a Github account so he could just comment on issues for us...

**Comment by carlydotwebsite** [comment]
lmao yeah, there's no reason why he couldn't or shouldn't have a github account :v join ussssss mark

**Comment by AdiraSlat** [comment]
Wounds are static, Stress is variable boxes.

**Comment by sublimemarch** [comment]
@MarkSlat : Should they carry over between games, though? Do we need do be able to track wounds and/or stress in the system?

**Comment by AdiraSlat** [comment]
Stress no. Wounds maybe. For now, they should just be blank boxes that STs can write words in during play.

**Comment by sublimemarch** [comment]
Rad. So we'll have blank boxes on the sheet for now, with tracking for them as an icebox issue.
