### ISSUE TITLE
Create views for creating and editing campaigns

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#28]
Need to create views to create a new campaign and edit an existing one. N.B. I added a field that sets a number of starting build points for characters to campaigns; I don't know if we actually want to have that in the form for now, but it's there if we want to use it. (e.g. if someone wanted to run a high-powered game where everyone has, like, 20 starting build points)

**Comment by AdiraSlat** [comment]
I like starting build points. I also recommend adding customization for milestones benefits and possibly groups of powers? But I don't think those are MVP, just starting build points would be.

**Comment by carlydotwebsite** [comment]
Ooh, yeah, that'd be good. It should be pretty easy to add down the line, I think. We can add an issue for that and label it as a long-term goal, maybe?

**Comment by carlydotwebsite** [comment]
@stephmarx also I was thinking that for the questionnaire components that we just worked in, we might use the jQuery UI sortable element, unless you know of something better? In case they want to re-order the questions.

**Comment by sublimemarch** [comment]
That sounds perfect.
