### ISSUE TITLE
Calculate validity of character build based on current stats

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#30]
Since the build costs are static, it seems like it'd be doable to check the validity of a character build:
- (No. of T1 powers \* 3) + (No. of T2 powers \* 5) + (No. of Knacks - 3, min 0) + (Item + Money + Allies - 2, min 0) = 14
- No. of Knacks >= 3
- Item + Money + Allies >= 2

We'd probably want to create a route to ping with an AJAX call whenever the user adds a power or a knack, or changes the item/money/allies fields, and then update the number of build points wherever we decide to display it.

**Comment by AdiraSlat** [comment]
We are giving character starting Knacks now, don't know if that is figured in. Everyone gets 3 knacks. Also, Mortals can buy up to 5 Knacks at chargen but have limited power selections (not currently finalized).

**Comment by carlydotwebsite** [comment]
Are non-mortals limited to their 3 starting knacks, or can they buy more?

**Comment by AdiraSlat** [comment]
They are limited to buying 3 more for a total of 6.

**Comment by carlydotwebsite** [comment]
Is that at character creation, or afterward? Just want to make sure I have it correct.

**Comment by AdiraSlat** [comment]
That is at character Creation only

**Comment by carlydotwebsite** [comment]
@MarkSlat Sorry, just want to make sure I've got the knacks thing correct. Are all of these true?
- Everyone gets three free knacks at character creation
- Mortals can buy five additional ones during character creation
- Non-mortals can buy three additional ones during character creation
- Everyone can buy more knacks later

**Comment by AdiraSlat** [comment]
That is correct
