### ISSUE TITLE
Add backstory and other descriptive fields

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#31]
Since we only played a one-shot with this I'm not sure what other fields might be more necessary for something like a LARP where storytellers/GMs might want to have players turn in a backstory or other information about their character. Thoughts???

**Comment by AdiraSlat** [comment]
Yes! As the originator of the questionnaire based backstory for DCP, I second this.

**Comment by carlydotwebsite** [comment]
Additional thoughts—I think maybe we could make a couple models which would allow us to implement different questionnaires (and different questionnaire lengths) for different games.

Each Campaign is associated with many QuestionnaireItems, which consist of a string that gives a question to respond to; each Character is associated with many QuestionnaireAnswers, which are linked to a QuestionnaireItem ID as well so that we know which question belongs with which answer.

**Comment by sublimemarch** [comment]
That makes perfect sense, let's do it.
