### ISSUE TITLE
Implement ability to add users as administrators to a campaign

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#32]
ticky boxes? from a select box? I don't know?

**Comment by AdiraSlat** [comment]
Select box probably (IF I KNOW WHAT THAT IS CORRECTLY?)

**Comment by sublimemarch** [comment]
@MarkSlat : Do you mean a drop down menu? I think the most elegant way to do this would be with a multiselect, maybe? Wait no. You shouldn't have to look through a list of a ton of users to find the one you're looking for. Ideally, I'd like to replicate the functionality of gmail's "to" field. You can start to type a person's name, and it pops up with suggestions. You can select multiple users, separated by commas.

**Comment by AdiraSlat** [comment]
I like that.

**Comment by carlydotwebsite** [comment]
we've actually used an input like that at work—I think [this](http://loopj.com/jquery-tokeninput/) is what we're going for, yeah?

**Comment by sublimemarch** [comment]
That's 100% what I want, yup.
