### ISSUE TITLE
Create character sheet view and editing form

### ISSUE THREAD

**Issue by carlydotwebsite** [stephmarx/infinite-mysteries-charsys#6]
Create a form as well as a static view for the character sheet.

**Comment by AdiraSlat** [comment]
I have ideas about how I want a sheet to look, best communicated through paper and pencil IMO

**Comment by carlydotwebsite** [comment]
scans/cameraphone images uploaded to the google docs folder are totally ok for us to work off of if that helps!

**Comment by carlydotwebsite** [comment]
@stephmarx question re: questionnaire items and campaign selection—how do you think we should manage this?

If they change the campaign on their sheet the questions might change, so should we have them pre-select a campaign before creating the character sheet? With the DCP system this wasn't an issue so much since the questions are universal. Though, since the answers are saved in the database regardless it's not as if they would lose data, but it might be alarming.

(Alt. we could show the questionnaire items on a separate page, I guess?)

**Comment by sublimemarch** [comment]
Discussed at meeting. Decision is to require user to select chronicle associated with character, then build character.
